name: build-and-release
run-name: Build the project final for release
permissions:
  contents: write
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
      branches:
          - main
      paths-ignore:
          - "azure-pipelines.yml"
  pull_request:
      paths-ignore:
          - "azure-pipelines.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.4.3,17.5)'
          msbuild-architecture: x64

      - name: Build app for release
        run: msbuild .\PrjCar\PrjCar\PrjCar.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
  